site_name: Today I Learned
site_url: https://simonmarquis.github.io/TIL/
repo_name: TIL
repo_url: https://github.com/SimonMarquis/TIL
edit_uri: edit/main/docs/
site_author: Simon Marquis
remote_branch: gh-pages

copyright: 'Copyright &copy; 2023 Simon Marquis'

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: lucide/moon-star
        name: Switch to system preference
  custom_dir: theme
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
  - pymdownx.blocks.admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - zensical.extensions.macros:
      verbose: true
      on_error_fail: true
      on_undefined: strict
      j2_block_start_string: '{{{%'
      j2_block_end_string: '%}}}'
      j2_variable_start_string: '{{{'
      j2_variable_end_string: '}}}'
      include_yaml:
        sample: data/sample.yaml
  - tables
  - toc:
      permalink: true

plugins:
  - meta
  - search
  # https://github.com/zensical/backlog/issues/18
  - git-revision-date-localized:
      enabled: !ENV [CI, GITHUB_ACTIONS, False]
      enable_creation_date: true
      exclude:
        - index.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SimonMarquis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/simonmarquis
    - icon: fontawesome/solid/user
      link: https://www.simon-marquis.fr
  key: value

nav:
  - index.md
  - android.md
  - bash.md
  - chrome.md
  - css.md
  - dagger.md
  - firebase.md
  - gerrit.md
  - git.md
  - github.md
  - gradle.md
  - html.md
  - intellij-idea.md
  - java.md
  - javascript.md
  - junit.md
  - kotlin.md
  - mac.md
  - markdown.md
  - miscellaneous.md
  - mkdocs.md
  - online-tools.md
  - open-source-projects.md
  - puzzlers.md
  - regex.md
  - sublime-merge.md
  - sublime-text.md
  - utils.md
  - windows.md
  - yaml.md

extra_css:
    - stylesheets/extra.css

strict: !ENV [MKDOCS_STRICT, True]
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
